install:
- npm install
language: node_js
node_js:
- '5'
- '5.1'
- '4'
- '4.2'
- '4.1'
- '4.0'
- iojs
deploy:
  provider: openshift
  user: resch.felix@gmail.com
  password:
    secure: k5MfMptBDxvFQYKdyoQ2msqzUh/oUIwNn3gQv2bJgfRrxaAKo+XlGPUv9N4OMe+pYsV9il8VtRUBCe34xFo6ufIPaKj1yiJxJfOZzGEXibSOG4T9R7rB2eIyjVh0CwdUoGgdJ1PVPK4ru0P/9Paa1TV7bgLK84RAq6R62tFzrmQD+2yIPBWVhwDz/x+HvHWnK6jgZiLhnbc/LSJmmaQGvMjoZt5C8FQswdWHSgC8L5cjboePBdyjfzea/8Ti405DSWHojUkSZIwwxhypeubcntLu8Ntcdwrl/lv9ScS+mSIm0A1kZvO+hBZKikM/2sSokt9mq3IEe9caewZ5BFOEG2cIOKIU8bTTT6BvLfIOKIDTbiacBsxAGph6O4jzbE2HWcNRI2hd4EE0TG04Qg7PPBhuDjuBIs6u5ZT+OD4XsWQ3csK/Dfyk2wre1SfHyV8a8c/Nz1CRJzvLoCsTKnOFDjLocW9iKVMx+qK9ul2hkfwuGwM91tLTBmipeWapLsmZPk080Ttjonufg+pHEEqWfOIvVq22BxcWR4gX5LXFFesOfxTozdQh5vw2UXyjoFg3XIgfoscqX/1FYqBa2LmKF8/0GAVWL00vV0DyLp4uAX7Fvd8bDTH/pGbE7KyasvkE4NfYUJttByDS2WFB9Wpg4w3QdMwg/3572o3Dtp1K2Eg=
  app: einkaufsliste
  domain: proxerread
  on:
    repo: FelixResch/einkaufsliste
